/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/
import React, { useRef } from 'react';
import { useGLTF } from '@react-three/drei';

export function CarModel(props) {
  const { nodes, materials } = useGLTF('/vr7_5_model.glb');
  
  // This is a placeholder structure. We'll likely need to adjust this
  // based on the actual structure of your GLB file.
  // We can log `nodes` and `materials` to the console to inspect them.
  console.log('Model Nodes:', nodes);
  console.log('Model Materials:', materials);

  return (
    <group {...props} dispose={null}>
      {/* 
        We iterate over all nodes in the GLTF scene.
        If a node is a mesh with geometry, we render it.
      */}
      {Object.values(nodes).map((node) => {
        if (node.isMesh) {
          return <mesh key={node.uuid} geometry={node.geometry} material={node.material} />;
        }
        return null;
      })}
    </group>
  );
}

useGLTF.preload('/vr7_5_model.glb'); 